// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Sam Yost. FormatFX is dual-licensed: AGPL-3.0-only (see LICENSE) or a commercial license (see LICENSING.md).

/**
 * editor/iconData.ts — the Fluent UI (MDL2) icon set that SharePoint's
 * `iconName` attribute actually renders, grouped by theme for the picker.
 *
 * GENERATED DATA — do not hand-edit. Regenerate with tools/gen-icons.mjs.
 * Source of truth: the icon export's "Renders In SP" column (every name here
 * is verified to render on a real list). Preview coverage is computed against
 * office-ui-fabric-core@11.0.0 (the version index.html loads); names it
 * can't draw are listed in NO_PREVIEW_ICONS and shown with a placeholder.
 * Names map 1:1 to the Fabric font class `ms-Icon--<Name>`.
 */

export interface IconGroup { name: string; icons: string[]; }

export const ICON_GROUPS: IconGroup[] = [
  { name: "Actions & Operations", icons: [
    'ActionCenter', 'Add', 'AddFavorite', 'AddFavoriteFill', 'AddFriend', 'AddIn',
    'AddLink', 'AddReaction', 'AddSpaceAfter', 'AddSpaceBefore', 'AddTo', 'Ascending',
    'Asterisk', 'CPlusPlus', 'Cancel', 'ChromeClose', 'Clear', 'ClearFilter',
    'ClearNight', 'Clicked', 'ClosedCaption', 'Crop', 'Cut', 'Delete',
    'DependencyAdd', 'DependencyRemove', 'Descending', 'DragObject', 'Drop', 'Edit',
    'EditCreate', 'EditMirrored', 'EditStyle', 'ExploreContent', 'ExploreContentSingle', 'ExploreData',
    'Eyedropper', 'Filter', 'FilterAscending', 'FilterDescending', 'FilterSolid', 'Filters',
    'Gather', 'Generate', 'Glimmer', 'Go', 'GoMirrored', 'InputAddress',
    'Insert', 'Leave', 'Lifesaver', 'Link', 'Link12', 'LogRemove',
    'Merge', 'MostyClearNight', 'Move', 'News', 'NewsSearch', 'ODLink',
    'ODLink12', 'OpenEnrollment', 'OpenWith', 'OpenWithMirrored', 'Paste', 'Personalize',
    'PublishContent', 'PublishCourse', 'Redo', 'Refresh', 'RegistryEditor', 'Remove',
    'RemoveContent', 'RemoveFilter', 'RemoveFromTrash', 'RemoveLink', 'RemoveLinkChain', 'RemoveLinkX',
    'Rename', 'RenewalCurrent', 'RenewalFuture', 'RepeatAll', 'RepeatOne', 'Reset',
    'ReturnToSession', 'Rotate', 'SIPMove', 'Save', 'SaveAll', 'SaveAndClose',
    'SaveAs', 'Search', 'SearchData', 'SearchIssue', 'SearchIssueMirrored', 'SearchNearby',
    'SetAction', 'Sort', 'Split', 'SplitObject', 'Subscribe', 'Sync',
    'Touch', 'Translate', 'Trim', 'TrimEnd', 'TurnRight', 'Undo',
    'Unfavorite', 'UnpublishContent', 'Unsubscribe',
  ] },
  { name: "Audio, Video & Images", icons: [
    'Album', 'AlbumRemove', 'AreaChart', 'Articles', 'BarChart4', 'BarChartHorizontal',
    'BarChartVertical', 'BarChartVerticalEdit', 'BarChartVerticalFill', 'BarChartVerticalFilter', 'Camera', 'Chart',
    'ChartSeries', 'ChartTemplate', 'ChartXAngle', 'ChartYAngle', 'DiagnosticDataBarTooltip', 'DonutChart',
    'DynamicList', 'DynamicSMBLogo', 'Dynamics365Logo', 'EditPhoto', 'FastForward', 'FastForwardEightX',
    'FastForwardFourX', 'FastForwardOneFiveX', 'FastForwardOneX', 'FastForwardPointFiveX', 'FastForwardTwoX', 'FlowChart',
    'FormatPainter', 'Forward', 'FrontCamera', 'FunnelChart', 'GIF', 'GiftCard',
    'Giftbox', 'GiftboxOpen', 'GiftboxSolid', 'Heart', 'HeartBroken', 'HeartFill',
    'IRMForward', 'IRMForwardMirrored', 'ImageCrosshair', 'ImageDiff', 'ImageInAR', 'ImagePixel',
    'ImageSearch', 'KnowledgeArticle', 'LineChart', 'MapLayers', 'Media', 'MediaAdd',
    'MicOff', 'MicOff2', 'MicrosoftFlowLogo', 'MicrosoftTranslatorLogo', 'MicrosoftTranslatorLogoBlue', 'MicrosoftTranslatorLogoGreen',
    'MusicInCollection', 'MusicInCollectionFill', 'MyMoviesTV', 'NavigateForward', 'NavigateForwardMirrored', 'OfficeVideoLogo',
    'OfficeVideoLogoFill', 'OfficeVideoLogoInverse', 'PartlyClearNight', 'PartlyCloudyDay', 'PartlyCloudyNight', 'PartlySunnyDay',
    'PartlySunnyFlurriesDay', 'PartlySunnyShowersDay', 'PartlySunnyShowersNight', 'PartlySunnyTStormsDay', 'Pause', 'PauseSolid',
    'Photo', 'Photo2', 'Photo2Add', 'Photo2Fill', 'Photo2Remove', 'PhotoBlock',
    'PhotoCollection', 'PhotoError', 'PhotoVideoMedia', 'Picture', 'PictureFill', 'PicturePosition',
    'PictureStretch', 'PictureTile', 'PivotChart', 'Play', 'PlayResume', 'PlayReverse',
    'PlayReverseResume', 'PlaySolid', 'PlaybackRate1x', 'PlayerSettings', 'ProcessingPause', 'ReceiptForward',
    'Record2', 'RewardsLogoArt64', 'Rewind', 'RewindEightX', 'RewindFourX', 'RewindOneFiveX',
    'RewindOneX', 'RewindPointFiveX', 'RewindTwoX', 'ScaleVolume', 'ScatterChart', 'ShoppingCart',
    'ShoppingCartSolid', 'SkipBack10', 'SkipForward30', 'Slider', 'SliderHandleSize', 'SliderThumb',
    'Slideshow', 'SmartGlassRemote', 'Speakers', 'StackColumnChart', 'StackedBarChart', 'StackedColumnChart2',
    'StackedColumnChart2Fill', 'StackedLineChart', 'Stop', 'StopSolid', 'StreamDiscover', 'StreamLogo',
    'Streaming', 'StreamingOff', 'SwitcherStartEnd', 'TrimStart', 'Video', 'Video360Generic',
    'VideoLightOff', 'VideoOff', 'VideoOff2', 'VideoSearch', 'VideoSolid', 'Volume0',
    'Volume1', 'Volume2', 'Volume3', 'VolumeDisabled', 'Webcam2', 'Webcam2Off',
  ] },
  { name: "Calendar & Events", icons: [
    'AddEvent', 'Calendar', 'CalendarAgenda', 'CalendarDay', 'CalendarMirrored', 'CalendarSettings',
    'CalendarSettingsMirrored', 'CalendarWeek', 'CalendarWorkWeek', 'CalendarYear', 'DateTime', 'DateTime12',
    'DateTime2', 'DateTimeMirrored', 'DisableUpdates', 'Event', 'Event12', 'EventDate',
    'EventDateMissed12', 'EventDeclined', 'EventInfo', 'EventTentative', 'EventTentativeMirrored', 'EventToDoLogo',
    'ForwardEvent', 'GotoToday', 'PostUpdate', 'PrimaryCalendar', 'RemoveEvent', 'ScheduleEventAction',
    'SearchCalendar', 'Snooze', 'SpecialEvent', 'UpdateRestore',
  ] },
  { name: "Charts & Analytics", icons: [
    'AnalyticsQuery', 'AnalyticsView', 'DiffInline', 'EntryDecline', 'GitGraph', 'GripperBarHorizontal',
    'GripperBarVertical', 'HideVisualFilter', 'IndentFirstLine', 'Insights', 'Line', 'LineSpacing',
    'LineStyle', 'LineThickness', 'NewAnalyticsQuery', 'PieDouble', 'PieSingle', 'PieSingleSolid',
    'ShowVisualFilter', 'SortLines', 'SortLinesAscending', 'Trending12', 'Underline', 'UpgradeAnalysis',
    'VennDiagram', 'VisioDiagram', 'VisioDiagramSync', 'VisuallyImpaired',
  ] },
  { name: "Chat & Feedback", icons: [
    'CalendarReply', 'CannedChat', 'Chat', 'ChatBot', 'ChatInviteFriend', 'ChatSolid',
    'Comment', 'CommentActive', 'CommentAdd', 'CommentNext', 'CommentPrevious', 'CommentUrgent',
    'Dislike', 'DocumentReply', 'Feedback', 'FileComment', 'Forum', 'IRMReply',
    'IRMReplyMirrored', 'IgnoreConversation', 'KaizalaLogo', 'Like', 'Message', 'MessageFill',
    'MessageFriendRequest', 'MuteChat', 'NoteReply', 'OfficeChat', 'PencilReply', 'PresenceChickletVideo',
    'QandA', 'QandAMirror', 'ReceiptReply', 'Reply', 'ReplyAll', 'ReplyAllAlt',
    'ReplyAllMirrored', 'ReplyAlt', 'ReplyMirrored', 'ResponsesMenu', 'SkypeMessage', 'TwitterLogo',
  ] },
  { name: "Devices & Accessories", icons: [
    'AnalyticsReport', 'CRMReport', 'ChromeFullScreen', 'Contrast', 'Export', 'ExportMirrored',
    'FabricTextHighlight', 'FabricTextHighlightComposite', 'FlashAuto', 'FlashOff', 'Flashlight', 'Focus',
    'FocusView', 'FullScreen', 'Headset', 'HeadsetSolid', 'Highlight', 'Import',
    'ImportAllMirrored', 'ImportMirrored', 'Important', 'Lamp', 'LaptopSecure', 'LaptopSelected',
    'Light', 'LightWeight', 'Lightbulb', 'LightningBolt', 'LightningSecure', 'MobileAngled',
    'MobileReport', 'MobileSelected', 'OEM', 'PC1', 'Plug', 'PowerButton',
    'PowerShell', 'PowerShell2', 'ProductVariant', 'Remote', 'ReportAdd', 'SaveToMobile',
    'Screen', 'ScreenCast', 'ScreenPreviewOn', 'Switch', 'SyncToPC', 'TVMonitor',
    'TVMonitorSelected', 'TableTotalRow', 'Tablet', 'TabletMode', 'TabletSelected', 'ThisPC',
    'USB', 'WifiEthernet',
  ] },
  { name: "Documents & Storage", icons: [
    'ActivityFeed', 'AddBookmark', 'AddNotes', 'AltText', 'Annotation', 'Archive',
    'ArchiveUndo', 'AssetLibrary', 'Attach', 'BookAnswers', 'BookingsLogo', 'BookmarkReport',
    'Bookmarks', 'BookmarksMirrored', 'Breadcrumb', 'BulletedListText', 'BulletedListTextMirrored', 'CalculatorNotEqualTo',
    'CheckListText', 'CheckListTextMirrored', 'ClassNotebookLogo16', 'ClassNotebookLogo32', 'ClassNotebookLogoFill16', 'ClassNotebookLogoFill32',
    'ClassNotebookLogoInverse', 'ClassNotebookLogoInverse16', 'ClassNotebookLogoInverse32', 'ContentFeed', 'ContextMenu', 'CortanaLogoReadyInner',
    'CortanaLogoReadyOuter', 'DecreaseIndentText', 'DecreaseIndentTextMirrored', 'Dictionary', 'DictionaryRemove', 'DocLibrary',
    'DockLeft', 'DockLeftMirrored', 'DockRight', 'DockerLogo', 'DocsLogoInverse', 'Document',
    'DocumentApproval', 'DocumentManagement', 'DocumentSearch', 'DocumentSet', 'Documentation', 'DoubleBookmark',
    'DownloadDocument', 'EditNote', 'EgnyteLogo', 'ExcelDocument', 'ExcelLogo', 'ExcelLogo16',
    'ExcelLogoInverse', 'ExcelLogoInverse16', 'FabricAssetLibrary', 'FabricDocLibrary', 'FabricFolder', 'FabricFolderConfirm',
    'FabricFolderFill', 'FabricFolderLink', 'FabricFolderSearch', 'FabricFolderUpload', 'FabricFormLibrary', 'FabricFormLibraryMirrored',
    'FabricMovetoFolder', 'FabricNewFolder', 'FabricOpenFolderHorizontal', 'FabricPictureLibrary', 'FabricPublicFolder', 'FabricReportLibrary',
    'FabricReportLibraryMirrored', 'FabricSyncFolder', 'FabricUnsyncFolder', 'FacebookLogo', 'Favicon', 'FieldReadOnly',
    'FileASPX', 'FileBug', 'FileCSS', 'FileCode', 'FileHTML', 'FileImage',
    'FileJAVA', 'FileLess', 'FileOff', 'FilePDB', 'FileRequest', 'FileSQL',
    'FileSass', 'FileSymlink', 'FileSystem', 'FileTemplate', 'FileTypeSolution', 'FileYML',
    'Fingerprint', 'FitPage', 'Folder', 'FolderFill', 'FolderHorizontal', 'FolderList',
    'FolderListMirrored', 'FolderOpen', 'FolderQuery', 'FolderSearch', 'FormLibrary', 'FormLibraryMirrored',
    'HintText', 'IncreaseIndentText', 'IncreaseIndentTextMirrored', 'InsertTextBox', 'Library', 'MSNLogo',
    'MSNVideos', 'MSNVolume', 'Memo', 'MostyCloudyTStormsNight', 'MoveToFolder', 'MusicNote',
    'NewFolder', 'NotExecuted', 'NoteForward', 'NotePinned', 'NumberedListText', 'NumberedListTextMirrored',
    'OneDriveFileVault', 'OneDriveFolder16', 'OneNoteEduLogoInverse', 'OneNoteLogo', 'OneNoteLogo16', 'OneNoteLogoInverse',
    'OneNoteLogoInverse16', 'OpenFile', 'OpenFolderHorizontal', 'PDF', 'Package', 'Packages',
    'Page', 'PageAdd', 'PageArrowRight', 'PageCheckedOut', 'PageCheckedin', 'PageData',
    'PageEdit', 'PageHeader', 'PageHeaderEdit', 'PageLeft', 'PageLink', 'PageList',
    'PageListFilter', 'PageLock', 'PageRemove', 'PageRight', 'PartlySunnyTStormsNight', 'PasswordField',
    'PasteAsText', 'PictureLibrary', 'PlainText', 'PowerPointDocument', 'PowerPointLogo', 'PowerPointLogo16',
    'PowerPointLogoInverse', 'PowerPointLogoInverse16', 'Print', 'ProtectedDocument', 'ProvisioningPackage', 'PublicFolder',
    'QuickNote', 'Read', 'ReadOutLoud', 'ReadingMode', 'ReopenPages', 'ReportDocument',
    'ReportLibrary', 'ReportLibraryMirrored', 'SearchBookmark', 'SingleBookmark', 'StaffNotebookLogo16', 'StaffNotebookLogo32',
    'StaffNotebookLogoFill16', 'StaffNotebookLogoFill32', 'StaffNotebookLogoInverted16', 'StaffNotebookLogoInverted32', 'StickyNotesOutlineAppIcon', 'SwayLogo16',
    'SwayLogo32', 'SwayLogoFill16', 'SwayLogoFill32', 'SwayLogoInverse', 'SyncFolder', 'TextAlignBottom',
    'TextAlignMiddle', 'TextAlignTop', 'TextBox', 'TextDocument', 'TextDocumentEdit', 'TextDocumentSettings',
    'TextField', 'TextOverflow', 'TextParagraphOption', 'TextRecognition', 'TextRotate270Degrees', 'TextRotate90Degrees',
    'TextRotateHorizontal', 'TextRotation', 'UnsyncFolder', 'VisioDocument', 'VisualsFolder', 'WordDocument',
    'WordLogo', 'WordLogo16', 'WordLogoInverse', 'WordLogoInverse16', 'ZipFolder',
  ] },
  { name: "Finance & Commerce", icons: [
    'ActivateOrders', 'AllCurrency', 'Bank', 'BorderDash', 'BorderDot', 'ChromeMinimize',
    'ChromeRestore', 'CloneToDesktop', 'CompanyDirectory', 'CompanyDirectoryMirrored', 'Coupon', 'Currency',
    'CustomerAssets', 'DeactivateOrders', 'EMI', 'Financial', 'FixedAssetManagement', 'Market',
    'MarketDown', 'MiniContract', 'MiniContractMirrored', 'Money', 'Product', 'ProductList',
    'ProductionFloorManagement', 'RealEstate', 'ReceiptCheck', 'ReceiptTentative', 'ReceiptTentativeMirrored', 'ReceiptUndelivered',
    'ReservationOrders', 'Savings', 'Sell', 'SemiboldWeight', 'Shop', 'StockDown',
    'StockUp', 'Suitcase', 'Taxi', 'Telemarketer', 'ToggleBorder', 'VisualsStore',
  ] },
  { name: "Food & Sports", icons: [
    'AustralianRules', 'AutoRacing', 'Balloons', 'Baseball', 'BeerMug', 'BirthdayCake',
    'Breakfast', 'Cafe', 'Cake', 'Calories', 'CaloriesAdd', 'Cat',
    'CategoryClassification', 'Chopsticks', 'Cocktails', 'Coffee', 'CoffeeScript', 'CollegeFootball',
    'CollegeHoops', 'ColumnFunction', 'CommunicationDetails', 'CommunicationDetailsMirrored', 'Communications', 'Cotton',
    'Cricket', 'Cycling', 'DuplicateRow', 'EatDrink', 'Education', 'Emoji',
    'Emoji2', 'EmojiNeutral', 'EmojiTabSymbols', 'EmptyRecycleBin', 'FangBody', 'Game',
    'Glasses', 'Golf', 'Guitar', 'HandsFree', 'Handwriting', 'Health',
    'HealthRefresh', 'Hospital', 'HourGlass', 'Medal', 'Medical', 'MergeDuplicate',
    'MoreSports', 'MountainClimbing', 'NUIFace', 'PanoIndicator', 'Parachute', 'PassiveAuthentication',
    'Pill', 'Presentation', 'Presentation12', 'ProFootball', 'ProductCatalog', 'Puzzle',
    'RecycleBin', 'Rocket', 'Rugby', 'Sad', 'SeeDo', 'Shirt',
    'SkiResorts', 'StackIndicator', 'Teeth', 'Tennis', 'Trophy', 'Trophy2',
    'Vacation', 'WavingHand', 'Wheelchair', 'Wines', 'XboxController',
  ] },
  { name: "History & Time", icons: [
    'AlarmClock', 'BufferTimeAfter', 'BufferTimeBefore', 'BufferTimeBoth', 'Clock', 'FontColorSwatch',
    'FullHistory', 'History', 'PictureCenter', 'Recent', 'ReminderPerson', 'ReminderTime',
    'Rotate90Clockwise', 'Rotate90CounterClockwise', 'ScreenTime', 'SentimentAnalysis', 'ShowTimeAs', 'Stopwatch',
    'TimeEntry', 'TimePicker', 'TimeSheet', 'Timer', 'WorldClock',
  ] },
  { name: "Layout & Style", icons: [
    'AlignCenter', 'AlignHorizontalCenter', 'AlignHorizontalLeft', 'AlignHorizontalRight', 'AlignJustify', 'AlignLeft',
    'AlignRight', 'AlignVerticalBottom', 'AlignVerticalTop', 'ArrangeByFrom', 'AutoEnhanceOff', 'AutoEnhanceOn',
    'AutoFillTemplate', 'AutoFitContents', 'AutoHeight', 'Back', 'BackgroundColor', 'Badge',
    'BidiLtr', 'BidiRtl', 'Blur', 'Bold', 'Brightness', 'Brush',
    'BucketColor', 'BucketColorFill', 'BulkUpload', 'ButtonControl', 'CampaignTemplate', 'Checkbox',
    'CheckboxComposite', 'CheckboxCompositeReversed', 'CheckboxFill', 'CheckboxIndeterminate', 'CheckboxIndeterminateCombo', 'CheckedOutByOther12',
    'CheckedOutByYou12', 'ChevronDown', 'ChevronDownEnd6', 'ChevronDownMed', 'ChevronDownSmall', 'ChevronFold10',
    'ChevronLeft', 'ChevronLeftEnd6', 'ChevronLeftMed', 'ChevronLeftSmall', 'ChevronRight', 'ChevronRightEnd6',
    'ChevronRightMed', 'ChevronRightSmall', 'ChevronUnfold10', 'ChevronUp', 'ChevronUpEnd6', 'ChevronUpMed',
    'ChevronUpSmall', 'ChromeBack', 'ChromeBackMirrored', 'ClearFormatting', 'ClearFormattingA', 'ClearFormattingEraser',
    'ClearSelection', 'ClearSelectionMirrored', 'ClosePane', 'ClosePaneMirrored', 'CollapseContent', 'CollapseContentSingle',
    'CollapseMenu', 'Color', 'ColorSolid', 'Combine', 'Combobox', 'CtrlButton',
    'DecreaseIndent', 'DecreaseIndentLegacy', 'DecreaseIndentMirrored', 'DensityComfy', 'DensityDefault', 'DiffSideBySide',
    'DistributeDown', 'DoubleChevronDown', 'DoubleChevronDown12', 'DoubleChevronDown8', 'DoubleChevronLeft', 'DoubleChevronLeft12',
    'DoubleChevronLeft8', 'DoubleChevronLeftMed', 'DoubleChevronLeftMedMirrored', 'DoubleChevronRight', 'DoubleChevronRight12', 'DoubleChevronRight8',
    'DoubleChevronUp', 'DoubleChevronUp12', 'DoubleChevronUp8', 'Down', 'Download', 'Dropdown',
    'EntryView', 'ExpandMenu', 'FitWidth', 'FlickDown', 'FlickLeft', 'FlickRight',
    'FlickUp', 'Font', 'FontColor', 'FontColorA', 'FontDecrease', 'FontIncrease',
    'FontSize', 'FontSize2', 'Footer', 'FullView', 'FullWidth', 'FullWidthEdit',
    'GripperDotsVertical', 'HalfAlpha', 'Header', 'Header1', 'Header2', 'Header3',
    'Header4', 'Hide', 'Hide2', 'Hide3', 'HorizontalDistributeCenter', 'IncreaseIndent',
    'IncreaseIndentHanging', 'IncreaseIndentHangingMirrored', 'IncreaseIndentLegacy', 'IncreaseIndentMirrored', 'Italic', 'Label',
    'LandscapeOrientation', 'LowerBrightness', 'MiniExpand', 'MiniExpandMirrored', 'MiniLink', 'More',
    'MoreVertical', 'Movers', 'MultiSelect', 'MultiSelectMirrored', 'Next', 'Octagon',
    'OpenInNewTab', 'OpenPane', 'OpenPaneMirrored', 'Orientation', 'Orientation2', 'Padding',
    'PaddingBottom', 'PaddingLeft', 'PaddingRight', 'PaddingTop', 'Pentagon', 'PopExpand',
    'Preview', 'PreviewLink', 'Previous', 'RadioBtnOff', 'RadioBtnOn', 'RadioBullet',
    'RedEye', 'RedEye12', 'Ribbon', 'RibbonSolid', 'RightDoubleQuote', 'SaveTemplate',
    'ScopeTemplate', 'ScrollUpDown', 'Section', 'Sections', 'SelectAll', 'Separator',
    'SidePanel', 'SidePanelMirrored', 'SizeLegacy', 'SortDown', 'SortUp', 'Spacer',
    'Spelling', 'Stack', 'Strikethrough', 'Tab', 'TabCenter', 'Tag',
    'TagSolid', 'ThumbnailView', 'ThumbnailViewMirrored', 'Tiles', 'Tiles2', 'ToggleFilled',
    'ToggleLeft', 'ToggleRight', 'ToggleThumb', 'Transition', 'TransitionEffect', 'TransitionPop',
    'TransitionPush', 'TriggerAuto', 'UnSetColor', 'UnstackSelected', 'Untag', 'Up',
    'Upload', 'VerticalDistributeCenter', 'View', 'ViewAll', 'ViewAll2', 'ViewInAR',
    'ViewOriginal', 'Waffle', 'Zoom', 'ZoomIn', 'ZoomOut', 'ZoomToFit',
  ] },
  { name: "Mail & Messaging", icons: [
    'Accept', 'AcceptMedium', 'AccessLogo', 'AccessibiltyChecker', 'AccountActivity', 'AccountBrowser',
    'AccountManagement', 'Accounts', 'AlertSettings', 'AlertSolid', 'ArrangeBringForward', 'ArrangeBringToFront',
    'ArrangeSendBackward', 'ArrangeSendToBack', 'CC', 'CreateMailRule', 'EaseOfAccess', 'EditMail',
    'EngineeringGroup', 'EventAccepted', 'ExchangeLogo', 'ExchangeLogoInverse', 'Fax', 'Inbox',
    'InboxActive', 'InboxCheck', 'InternetSharing', 'Mail', 'MailAlert', 'MailAttached',
    'MailCheck', 'MailFill', 'MailForward', 'MailForwardMirrored', 'MailLink', 'MailLowImportance',
    'MailOptions', 'MailPause', 'MailReminder', 'MailRepeat', 'MailReply', 'MailReplyAll',
    'MailReplyAllMirrored', 'MailReplyMirrored', 'MailSchedule', 'MailSecure', 'MailSolid', 'MailTentative',
    'MailTentativeMirrored', 'MailUndelivered', 'Manufacturing', 'Megaphone', 'NewMail', 'PeopleAlert',
    'PrintfaxPrinterFile', 'ProgressRing5', 'ProgressRingDots', 'PublicCalendar', 'PublicContactCard', 'PublicContactCardMirrored',
    'PublicEmail', 'RecurringEvent', 'RecurringTask', 'RemoveOccurrence', 'Ringer', 'RingerActive',
    'RingerOff', 'RingerRemove', 'RingerSolid', 'Send', 'SendMirrored', 'ShieldAlert',
    'Soccer', 'SyncOccurence', 'TemporaryAccessPass', 'UnsyncOccurence', 'Vaccination', 'VoicemailForward',
    'VoicemailIRM', 'VoicemailReply', 'WorkItemAlert',
  ] },
  { name: "Maps & Location", icons: [
    'AddToShoppingList', 'Globe', 'Globe2', 'GlobeFavorite', 'Location', 'LocationDot',
    'LocationFill', 'LocationOutline', 'MapDirections', 'Nav2DMapView', 'ParkingLocation', 'ParkingLocationMirrored',
    'Pin', 'PinSolid', 'Pinned', 'PinnedFill', 'PinnedSolid', 'RectangularClipping',
    'RemoveFromShoppingList', 'Unpin', 'World',
  ] },
  { name: "Math & Programming", icons: [
    'AlignVerticalCenter', 'AspectRatio', 'BranchCommit', 'BranchCompare', 'BranchFork', 'BranchFork2',
    'BranchMerge', 'BranchPullRequest', 'BranchSearch', 'BranchShelveset', 'CSS', 'CSharp',
    'Calculator', 'CalculatorAddition', 'CalculatorDelta', 'CalculatorEqualTo', 'CalculatorMultiply', 'CalculatorPercentage',
    'CalculatorSubtract', 'Code', 'CodeEdit', 'CommandPrompt', 'Compare', 'CompareUneven',
    'Copy', 'CopyEdit', 'DOM', 'Decimals', 'DefaultRatio', 'Diagnostic',
    'DrillDown', 'DrillExpand', 'DrillShow', 'DrillThrough', 'Embed', 'EntityExtraction',
    'Equalizer', 'FSharp', 'GUID', 'GitFork', 'IOT', 'IoTSecure',
    'JS', 'MachineLearning', 'MaximumValue', 'MetricsFailure', 'MetricsUsage', 'MinimumValue',
    'ModelingView', 'NormalWeight', 'Number', 'NumberSequence', 'NumberSymbol', 'OpenSource',
    'PY', 'Parameter', 'PasteAsCode', 'PollResults', 'QRCode', 'Quantity',
    'R', 'RawSource', 'Repo', 'Robot', 'ScaleUp', 'Script',
    'ShowResults', 'ShowResultsMirrored', 'SiteScan', 'Source', 'SpeedHigh', 'Subscript',
    'SubstitutionsIn', 'Superscript', 'TestAdd', 'TestBeaker', 'TestCase', 'TestParameter',
    'TestRemove', 'TestSuite', 'Total', 'VB', 'Variable', 'Variable2',
    'Variable3', 'VersionControlPush', 'Weights', 'eDiscovery',
  ] },
  { name: "Network & Connectivity", icons: [
    'BlobStorage', 'Database', 'DatabaseSync', 'DatabaseView', 'IDBadge', 'LinkedDatabase',
    'MasterDatabase', 'OfflineStorage', 'PromotedDatabase', 'SQLAnalyticsPool', 'StorageAcount', 'StorageOptical',
    'VerifiedBrand',
  ] },
  { name: "People & Groups", icons: [
    'AddConnection', 'AddGroup', 'AddOnlineMeeting', 'AddPhone', 'AssessmentGroup', 'AssessmentGroupTemplate',
    'BlockContact', 'CalculatorGroup', 'CellPhone', 'ConnectContacts', 'ConnectVirtualMachine', 'Contact',
    'ContactCard', 'ContactCardSettings', 'ContactCardSettingsMirrored', 'ContactHeart', 'ContactInfo', 'ContactLink',
    'ContactList', 'ContactLock', 'DataConnectionLibrary', 'DeclineCall', 'DelveAnalytics', 'DelveAnalyticsLogo',
    'DelveLogo', 'DelveLogoFill', 'DelveLogoInverse', 'Dialpad', 'DisconnectVirtualMachine', 'EditContact',
    'ExternalUser', 'FabricDataConnectionLibrary', 'FabricNetworkFolder', 'FabricUserFolder', 'Family', 'FluidLogo',
    'FollowUser', 'GitHubLogo', 'Group', 'GroupList', 'GroupObject', 'GroupRemove',
    'GroupedAscending', 'GroupedDescending', 'GroupedList', 'HardDriveGroup', 'HomeGroup', 'IncomingCall',
    'JoinOnlineMeeting', 'LeaveUser', 'LockShare', 'Microphone', 'MicrosoftStaffhubLogo', 'MyNetwork',
    'NetworkTower', 'NewTeamProject', 'Org', 'PageShared', 'PartyLeader', 'People',
    'PeopleAdd', 'PeopleBlock', 'PeoplePause', 'PeopleRepeat', 'Phone', 'PlugConnected',
    'PlugDisconnected', 'ProfileSearch', 'RecruitmentManagement', 'ReminderGroup', 'RowsGroup', 'SecurityGroup',
    'Share', 'SharedDatabase', 'ShareiOS', 'Sharepoint2013LogoInverse', 'SharepointAppIcon16', 'SharepointLogo',
    'SharepointLogoInverse', 'SkypeArrow', 'SkypeCheck', 'SkypeClock', 'SkypeForBusinessLogo', 'SkypeForBusinessLogo16',
    'SkypeForBusinessLogoFill', 'SkypeForBusinessLogoFill16', 'SkypeLogo', 'SkypeLogo16', 'SkypeMinus', 'SkypeSlash',
    'SocialListeningLogo', 'StatusErrorFull', 'StepShared', 'StepSharedAdd', 'StepSharedInsert', 'SwitchUser',
    'TableGroup', 'TagGroup', 'TaskGroup', 'TaskGroupMirrored', 'TeamFavorite', 'TeamsLogo',
    'TeamsLogo16', 'TeamsLogoInverse', 'Teamwork', 'TemporaryUser', 'TextCallout', 'TextDocumentShared',
    'TransferCall', 'TriggerUser', 'UngroupObject', 'UnknownCall', 'UserEvent', 'UserFollowed',
    'UserGauge', 'UserOptional', 'UserPause', 'UserRemove', 'UserSync', 'UserWarning',
    'VariableGroup', 'ViewListGroup', 'WipePhone', 'WorkforceManagement', 'YammerLogo',
  ] },
  { name: "Security & Compliance", icons: [
    'AnchorLock', 'AssignPolicy', 'AzureKeyVault', 'Blocked', 'Blocked12', 'Blocked2',
    'BlockedSite', 'BlockedSolid', 'BranchLocked', 'BugBlock', 'ChangeEntitlements', 'DRM',
    'DefenderApp', 'DefenderBadge12', 'DefenderTVM', 'Door', 'Encryption', 'EntitlementPolicy',
    'EntitlementRedemption', 'HardDriveLock', 'HardDriveUnlock', 'HexaditeInvestigation', 'HexaditeInvestigationCancel', 'HexaditeInvestigationSemiAuto',
    'HorizontalTabKey', 'KeyPhraseExtraction', 'LifesaverLock', 'Lock', 'Lock12', 'LockSolid',
    'MarkAsProtected', 'OrderLock', 'Phishing', 'PhishingCampaign', 'PhishingHook', 'ProHockey',
    'ProtectRestrict', 'ProtectionCenterLogo32', 'ReportHacked', 'ReportLock', 'ReturnKey', 'RevToggleKey',
    'SecurityTest', 'Shield', 'ShieldSolid', 'URLBlock', 'Unlock', 'UnlockSolid',
  ] },
  { name: "Settings & Administration", icons: [
    'AADLogo', 'ATPLogo', 'Admin', 'AdminALogo32', 'AdminALogoFill32', 'AdminALogoInverse32',
    'AdminCLogoInverse32', 'AdminDLogoInverse32', 'AdminELogoInverse32', 'AdminLLogoInverse32', 'AdminMLogoInverse32', 'AdminOLogoInverse32',
    'AdminPLogoInverse32', 'AdminSLogoInverse32', 'AdminYLogoInverse32', 'AllApps', 'AllAppsMirrored', 'AmazonWebServicesLogo',
    'AnalyticsLogo', 'AndroidLogo', 'ApacheIvyLogo32', 'ApacheMavenLogo', 'AppIconDefault', 'AppIconDefaultAdd',
    'AppIconDefaultList', 'AuthenticatorApp', 'AutomateFlow', 'AzureAPIManagement', 'AzureDataExplorer', 'AzureLogo',
    'AzureServiceEndpoint', 'BingLogo', 'BitbucketLogo32', 'Blog', 'BoxLogo', 'Brunch',
    'BusinessCenterLogo', 'CPlusPlusLanguage', 'CRMProcesses', 'CRMServices', 'Certificate', 'CertifiedDatabase',
    'ChronosLogo', 'ClassroomLogo', 'Cloud', 'CloudAdd', 'CloudDownload', 'CloudEdit',
    'CloudImportExport', 'CloudLink', 'CloudSearch', 'CloudSecure', 'CloudUpload', 'CloudWeather',
    'Cloudy', 'CommonDataServiceCDS', 'ComplianceAudit', 'ContentSettings', 'CortanaLogoBeckonInner', 'CortanaLogoBeckonOuter',
    'CortanaLogoInner', 'CortanaLogoOuter', 'CostContralLedgerAdmin', 'CustomizeToolbar', 'D365CoreHR', 'D365CustomerInsights',
    'D365TalentInsight', 'D365TalentLearn', 'DataManagementSettings', 'Dataflows', 'DataflowsLink', 'DeveloperTools',
    'DeviceRun', 'DropboxLogo', 'EdgeOldLogo', 'EmojiDisappointed', 'EraseTool', 'F12DevTools',
    'FastMode', 'FilterSettings', 'Flow', 'FlowTemplate', 'Flower', 'FormProcessing',
    'GallatinLogo', 'GenericScan', 'GenericScanFilled', 'GitLogo', 'GoogleDriveLogo', 'GoogleDriveLogoBottomBlue',
    'GoogleDriveLogoLeftGreen', 'GoogleDriveLogoRightYellow', 'GradleLogo32', 'GripperTool', 'InkingTool', 'InstallToDrive',
    'Installation', 'IntermittentCloudsDay', 'IntermittentCloudsNight', 'JavaLogo', 'JavaScriptLanguage', 'JenkinsLogo',
    'KeubernetesLogo', 'LearningTools', 'LinkedInLogo', 'LinuxLogo32', 'LiveSite', 'LocalAdmin',
    'LocaleLanguage', 'LyncLogo', 'M365InvoicingLogo', 'MTMLogo', 'ManagerSelfService', 'MapPin',
    'MapPin12', 'MapPinSolid', 'MarkDownLanguage', 'MetricsInstall', 'MiracastLogoLarge', 'MixerLogo',
    'MostyCloudyFlurriesDay', 'MostyCloudyFlurriesNight', 'MostyCloudyShowersDay', 'MostyCloudyTStormsDay', 'NPMLogo', 'NonprofitLogo32',
    'NugetLogo', 'OfficeAddinsLogo', 'OfficeAssistantLogo', 'OfficeFormsLogo', 'OfficeFormsLogo16', 'OfficeFormsLogo24',
    'OfficeFormsLogoInverse', 'OfficeFormsLogoInverse16', 'OfficeFormsLogoInverse24', 'OfficeLogo', 'OfficeStoreLogo', 'OneDriveLogo',
    'OutlookLogo', 'OutlookLogo16', 'OutlookLogoInverse', 'OutlookLogoInverse16', 'ParatureLogo', 'Permissions',
    'PowerApps', 'PowerApps2Logo', 'PowerAppsLogo', 'PowerAppsTemplate', 'PowerBILogo', 'PowerBILogo16',
    'PowerBILogoBackplate16', 'PowerVirtualAgentsLogo', 'Processing', 'ProcessingCancel', 'ProcessingRun', 'PublisherLogo',
    'PublisherLogo16', 'PublisherLogoInverse16', 'PythonLanguage', 'PythonLogoBlue', 'PythonLogoYellow', 'ReactLogo',
    'ReceiptProcessing', 'Repair', 'Rerun', 'RewardsLogo', 'RubyGemsLogo', 'Running',
    'RustLanguageLogo', 'SVNLogo', 'SchoolDataSyncLogo', 'SearchAndApps', 'Server', 'ServerEnviroment',
    'ServerProcesses', 'ServiceOff', 'Settings', 'SettingsAdd', 'SettingsSecure', 'SettingsSync',
    'ShopServer', 'StoreLogo16', 'StoreLogoMed20', 'SwiftLogo', 'System', 'TFVCLogo',
    'Toolbox', 'TriggerApproval', 'TypeScriptLanguage', 'VisioLogo', 'VisioLogo16', 'VisioLogoInverse',
    'VisioLogoInverse16', 'VisualBasicLanguage', 'VisualStudioIDELogo32', 'VisualStudioLogo', 'WebComponents', 'WebEnvironment',
    'WebPublish', 'WebTemplate', 'Website', 'WindowsLogo', 'XamarinLogo', 'XboxLogo',
    'XboxOneConsole', 'iOSAppStoreLogo',
  ] },
  { name: "Shapes & Symbols", icons: [
    'CircleAddition', 'CircleFill', 'CircleHalfFull', 'CirclePause', 'CirclePlus', 'CircleRing',
    'CircleShape', 'CircleStop', 'CubeShape', 'Diamond', 'DropShape', 'Ellipse',
    'FullCircleMask', 'HalfCircle', 'Hexagon', 'HighlightMappedShapes', 'IncidentTriangle', 'LocationCircle',
    'QuarterCircle', 'RectangleShape', 'RightTriangle', 'Shapes', 'SkypeCircleArrow', 'SkypeCircleCheck',
    'SkypeCircleClock', 'SkypeCircleMinus', 'SkypeCircleSlash', 'SquareShape', 'StatusCircleBlock', 'StatusCircleBlock2',
    'StatusCircleCheckmark', 'StatusCircleErrorX', 'StatusCircleExclamation', 'StatusCircleInfo', 'StatusCircleInner', 'StatusCircleOuter',
    'StatusCircleQuestionMark', 'StatusCircleRing', 'StatusCircleSync', 'StatusTriangle', 'StatusTriangleExclamation', 'StatusTriangleInner',
    'StatusTriangleOuter', 'ThreeQuarterCircle', 'TriangleDown12', 'TriangleLeft12', 'TriangleRight12', 'TriangleShape',
    'TriangleUp12',
  ] },
  { name: "Status & Progress", icons: [
    'AwayStatus', 'Bug', 'BugAction', 'BugSolid', 'BugSync', 'BugWarning',
    'Bullseye', 'BullseyeTarget', 'BullseyeTargetEdit', 'CheckMark', 'ColumnQuestion', 'ColumnQuestionMirrored',
    'Commitments', 'Completed', 'ConstructionCone', 'DeviceBug', 'Error', 'ErrorBadge',
    'ExerciseTracker', 'EyeShadow', 'FavoriteStar', 'FavoriteStarFill', 'Flag', 'Help',
    'HelpMirrored', 'HomeVerify', 'IconSetsFlag', 'Info', 'Info2', 'InfoSolid',
    'InformationBarriers', 'InternalInvestigation', 'IssueTracking', 'IssueTrackingMirrored', 'LookupEntities', 'OutlookSpacesBucket',
    'ProgressLoopInner', 'ProgressLoopOuter', 'Questionnaire', 'QuestionnaireMirrored', 'ReportWarning', 'Starburst',
    'Step', 'StepInsert', 'SunQuestionMark', 'SurveyQuestions', 'SyncStatus', 'TagUnknown',
    'TagUnknown12', 'TagUnknown12Mirror', 'TagUnknownMirror', 'TestStep', 'Trackers', 'TrackersMirrored',
    'Unknown', 'UnknownMirrored', 'WaitlistConfirm', 'WaitlistConfirmMirrored', 'Warning', 'Warning12',
    'WarningSolid', 'WifiWarning4',
  ] },
  { name: "Tables & Grids", icons: [
    'AddField', 'AddTable', 'ArrowDownRight8', 'ArrowDownRightMirrored8', 'ArrowTallDownLeft', 'ArrowTallDownRight',
    'ArrowTallUpLeft', 'ArrowTallUpRight', 'ArrowUpRight', 'ArrowUpRight8', 'ArrowUpRightMirrored8', 'BrowserTab',
    'BulletedList', 'BulletedList2', 'BulletedList2Mirrored', 'BulletedListBullet', 'BulletedListBulletMirrored', 'BulletedListMirrored',
    'BulletedTreeList', 'CalculatedTable', 'CheckList', 'CheckListCheck', 'CheckListCheckMirrored', 'Column',
    'ColumnLeftTwoThirds', 'ColumnLeftTwoThirdsEdit', 'ColumnOptions', 'ColumnRightTwoThirds', 'ColumnRightTwoThirdsEdit', 'ColumnSigma',
    'ColumnVerticalSection', 'ColumnVerticalSectionEdit', 'Crown', 'CrownSolid', 'CustomList', 'CustomListMirrored',
    'DecreaseIndentArrow', 'DecreaseIndentArrowMirrored', 'DeleteColumns', 'DeleteRows', 'DeleteRowsMirrored', 'DeleteTable',
    'DoubleColumn', 'DoubleColumnEdit', 'DoubleDownArrow', 'EditTable', 'FavoriteList', 'FieldChanged',
    'FieldEmpty', 'FieldFilled', 'FieldNotChanged', 'FieldRequired', 'FiveTileGrid', 'FixedColumnWidth',
    'GridViewLarge', 'GridViewMedium', 'GridViewSmall', 'IncreaseIndentArrow', 'IncreaseIndentArrowMirrored', 'InsertColumnsLeft',
    'InsertColumnsRight', 'InsertRowsAbove', 'InsertRowsBelow', 'LargeGrid', 'List', 'ListMirrored',
    'NumberField', 'NumberedList', 'NumberedListMirrored', 'NumberedListNumber', 'NumberedListNumberMirrored', 'QuadColumn',
    'QueryList', 'RepeatHeaderRows', 'RowsChild', 'ShowGrid', 'SingleColumn', 'SingleColumnEdit',
    'SnapToGrid', 'TabOneColumn', 'TabThreeColumn', 'TabTwoColumn', 'Table', 'TableBrandedColumn',
    'TableBrandedRow', 'TableColumn', 'TableComputed', 'TableFirstColumn', 'TableHeaderRow', 'TableLastColumn',
    'TableLink', 'TripleColumn', 'TripleColumnEdit', 'TripleColumnWide', 'Uneditable', 'Uneditable2',
    'Uneditable2Mirrored', 'UneditableMirrored', 'ViewList', 'ViewListTree',
  ] },
  { name: "Tasks & Projects", icons: [
    'AddWork', 'Airplane', 'AirplaneSolid', 'AutoDeploySettings', 'BIDashboard', 'Backlog',
    'BacklogBoard', 'BacklogList', 'Boards', 'Build', 'BuildDefinition', 'BuildIssue',
    'BuildQueue', 'BuildQueueNew', 'CSharpLanguage', 'Childof', 'ClipboardList', 'ClipboardListMirrored',
    'D365ProjectOperations', 'DashboardAdd', 'Deploy', 'DietPlanNotebook', 'ExternalBuild', 'FSharpLanguage',
    'FunctionalManagerDashboard', 'GoToDashboard', 'KeyboardClassic', 'Onboarding', 'PenWorkspace', 'PlanView',
    'PlannerLogo', 'ProcessMetaTask', 'ProductRelease', 'Project2019Document', 'ProjectCollection', 'ProjectDocument',
    'ProjectLogo16', 'ProjectLogo32', 'ProjectLogoInverse', 'Redeploy', 'ReleaseDefinition', 'ReleaseGate',
    'ReleaseGateCheck', 'ReleaseGateError', 'Sprint', 'Storyboard', 'TaskList', 'TaskLogo',
    'TaskManager', 'TaskManagerMirrored', 'Taskboard', 'TestPlan', 'Timeline', 'TimelineDelivery',
    'TimelineMatrixView', 'TimelineProgress', 'ToDoLogoBottom', 'ToDoLogoInverse', 'ToDoLogoOutline', 'ToDoLogoTop',
    'VSTSAltLogo1', 'VSTSAltLogo2', 'VSTSLogo', 'ViewDashboard', 'WebAppBuilderFragment', 'WebAppBuilderFragmentCreate',
    'WebAppBuilderFragmentLock', 'WebAppBuilderFragmentTest', 'WebAppBuilderModule', 'WebAppBuilderModuleLock', 'WebAppBuilderModuleTest', 'WebAppBuilderSlot',
    'WhiteBoardApp16', 'WhiteBoardApp32', 'Work', 'WorkFlow', 'WorkItem', 'WorkItemBar',
    'WorkItemBug',
  ] },
  { name: "Vehicles & Travel", icons: [
    'AddHome', 'AirTickets', 'Arrivals', 'Assign', 'Broom', 'Bus',
    'BusinessHoursSign', 'Car', 'CaretBottomLeftCenter8', 'CaretBottomRightCenter8', 'CaretDown8', 'CaretHollow',
    'CaretHollowMirrored', 'CaretLeft8', 'CaretRight', 'CaretRight8', 'CaretTopLeftCenter8', 'CaretTopRightCenter8',
    'CaretUp8', 'CityNext', 'CityNext2', 'CompassNW', 'DeliveryTruck', 'Design',
    'DriverOff', 'ExternalGit', 'ExternalTFVC', 'ExternalXAML', 'Ferry', 'FocalPoint',
    'GlobalNavButton', 'GlobalNavButtonActive', 'GreetingCard', 'HardDrive', 'Home', 'HomeDropdown',
    'HomeSolid', 'InsertSignatureLine', 'NavigateBack', 'NavigateBackMirrored', 'NavigateExternalInline', 'NavigationFlipper',
    'OfflineOneDriveParachute', 'OfflineOneDriveParachuteDisabled', 'OneDriveAdd', 'POI', 'PaymentCard', 'Relationship',
    'Room', 'SDCard', 'SecondaryNav', 'SignOut', 'Signin', 'SixPointStar',
    'Street', 'StreetsideSplitMinimize', 'Ticket', 'Toll', 'TouchPointer', 'Train',
    'TrainSolid', 'TwelvePointStar',
  ] },
  { name: "Weather & Climate", icons: [
    'AutoFitWindow', 'BackToWindow', 'BlowingSnow', 'BrowserScreenShot', 'BrowserTabScreenshot', 'ChoiceColumn',
    'DesktopScreenshot', 'DeviceOff', 'Devices2', 'Devices3', 'Devices4', 'Duststorm',
    'Fog', 'Freezing', 'FreezingRain', 'Frigid', 'HailDay', 'HailNight',
    'HazyDay', 'HazyNight', 'HistoricalWeather', 'Hot', 'Hotel', 'Ice',
    'LightSnow', 'MostySunnyDay', 'OfficeCatchUp', 'OpenInNewWindow', 'OutOfOffice', 'Precipitation',
    'Rain', 'RainShowersDay', 'RainShowersNight', 'RainSnow', 'ResetDevice', 'ShakeDevice',
    'Showers', 'Sleet', 'Snow', 'SnowShowerDay', 'SnowShowerNight', 'Snowflake',
    'Squalls', 'SunAdd', 'Sunny', 'Thunderstorms', 'Umbrella', 'WaffleOffice365',
    'WindDirection', 'WindowEdit',
  ] },
];

/** Every renderable icon name, flattened (deduped, sorted). */
export const ALL_ICONS: string[] = [...new Set(ICON_GROUPS.flatMap((g) => g.icons))].sort();

/** SP-valid names the bundled Fabric font can't preview (shown with a placeholder). */
export const NO_PREVIEW_ICONS: ReadonlySet<string> = new Set([
  'AcceptMedium', 'AddConnection', 'AddField', 'AddSpaceAfter', 'AddSpaceBefore', 'AddTable',
  'AltText', 'AmazonWebServicesLogo', 'AndroidLogo', 'ApacheIvyLogo32', 'ApacheMavenLogo', 'ArchiveUndo',
  'AssignPolicy', 'AutoDeploySettings', 'AutoFitContents', 'AutoFitWindow', 'AutomateFlow', 'AzureDataExplorer',
  'BitbucketLogo32', 'BlobStorage', 'BoxLogo', 'BugAction', 'BugBlock', 'BugSync',
  'BugWarning', 'CC', 'CalculatedTable', 'CalculatorDelta', 'CalculatorGroup', 'CategoryClassification',
  'CheckboxIndeterminateCombo', 'ChoiceColumn', 'ChronosLogo', 'CircleShape', 'Clicked', 'CloudEdit',
  'CloudLink', 'CloudSearch', 'CloudSecure', 'Column', 'ColumnFunction', 'ColumnQuestion',
  'ColumnQuestionMirrored', 'ColumnSigma', 'CommonDataServiceCDS', 'CommunicationDetails', 'CommunicationDetailsMirrored', 'CompareUneven',
  'ContactLock', 'ContentFeed', 'ContentSettings', 'CopyEdit', 'CortanaLogoBeckonInner', 'CortanaLogoBeckonOuter',
  'CortanaLogoInner', 'CortanaLogoOuter', 'CortanaLogoReadyInner', 'CortanaLogoReadyOuter', 'CostContralLedgerAdmin', 'CtrlButton',
  'Currency', 'CustomerAssets', 'D365CoreHR', 'D365CustomerInsights', 'D365ProjectOperations', 'DatabaseView',
  'DateTime12', 'DecreaseIndent', 'DecreaseIndentMirrored', 'DefenderApp', 'DefenderBadge12', 'DensityComfy',
  'DensityDefault', 'DeviceBug', 'DeviceOff', 'DeviceRun', 'DockerLogo', 'DriverOff',
  'DropShape', 'DropboxLogo', 'DynamicList', 'EdgeOldLogo', 'EditTable', 'EgnyteLogo',
  'EntityExtraction', 'ExternalGit', 'ExternalUser', 'FabricFolderLink', 'FabricFolderUpload', 'FacebookLogo',
  'FastForwardEightX', 'FastForwardFourX', 'FastForwardOneFiveX', 'FastForwardOneX', 'FastForwardPointFiveX', 'FastForwardTwoX',
  'FileOff', 'FileSystem', 'FilterAscending', 'FilterDescending', 'FixedAssetManagement', 'FixedColumnWidth',
  'FlashAuto', 'FlashOff', 'FlowTemplate', 'FluidLogo', 'FocusView', 'FontSize2',
  'FormProcessing', 'FormatPainter', 'FreezingRain', 'FullView', 'Gather', 'GiftboxSolid',
  'GitFork', 'GitHubLogo', 'GitLogo', 'GoogleDriveLogo', 'GoogleDriveLogoBottomBlue', 'GoogleDriveLogoLeftGreen',
  'GoogleDriveLogoRightYellow', 'GradleLogo32', 'GroupRemove', 'HazyDay', 'HazyNight', 'HealthRefresh',
  'HexaditeInvestigation', 'HexaditeInvestigationCancel', 'HexaditeInvestigationSemiAuto', 'HideVisualFilter', 'HomeDropdown', 'Hot',
  'IOT', 'Ice', 'ImageInAR', 'InboxActive', 'IncreaseIndent', 'IncreaseIndentHanging',
  'IncreaseIndentHangingMirrored', 'IncreaseIndentMirrored', 'IndentFirstLine', 'InputAddress', 'Insights', 'IntermittentCloudsDay',
  'IntermittentCloudsNight', 'IoTSecure', 'JavaLogo', 'JenkinsLogo', 'KeubernetesLogo', 'KeyPhraseExtraction',
  'LearningTools', 'LeaveUser', 'LightSnow', 'LightningSecure', 'LinuxLogo32', 'LiveSite',
  'LocalAdmin', 'LockShare', 'MSNVolume', 'MTMLogo', 'MachineLearning', 'MailLink',
  'MailSecure', 'MapPin12', 'MessageFriendRequest', 'MetricsFailure', 'MetricsInstall', 'MetricsUsage',
  'MiracastLogoLarge', 'MixerLogo', 'MobileAngled', 'MostyClearNight', 'MostyCloudyFlurriesDay', 'MostyCloudyFlurriesNight',
  'MostyCloudyShowersDay', 'MostyCloudyTStormsDay', 'MostyCloudyTStormsNight', 'MostySunnyDay', 'MyNetwork', 'NPMLogo',
  'NUIFace', 'NonprofitLogo32', 'Number', 'NumberedListMirrored', 'ODLink', 'ODLink12',
  'OfficeCatchUp', 'OneDriveFileVault', 'OrderLock', 'OutlookSpacesBucket', 'ParatureLogo', 'PartlyClearNight',
  'PartlySunnyDay', 'PartlySunnyFlurriesDay', 'PartlySunnyShowersDay', 'PartlySunnyShowersNight', 'PartlySunnyTStormsDay', 'PartlySunnyTStormsNight',
  'PauseSolid', 'PhishingCampaign', 'PhishingHook', 'PhotoBlock', 'PhotoError', 'PinSolid',
  'PlaySolid', 'PopExpand', 'PowerAppsTemplate', 'PowerVirtualAgentsLogo', 'ProcessingCancel', 'ProcessingPause',
  'ProcessingRun', 'ProgressRing5', 'Project2019Document', 'ProvisioningPackage', 'PythonLogoBlue', 'PythonLogoYellow',
  'ReactLogo', 'ReceiptProcessing', 'RedEye12', 'RegistryEditor', 'RemoveContent', 'RepeatHeaderRows',
  'Reset', 'RewardsLogo', 'RewardsLogoArt64', 'RewindEightX', 'RewindFourX', 'RewindOneFiveX',
  'RewindOneX', 'RewindPointFiveX', 'RewindTwoX', 'RingerActive', 'RubyGemsLogo', 'RustLanguageLogo',
  'SDCard', 'SQLAnalyticsPool', 'SVNLogo', 'Screen', 'ScreenPreviewOn', 'ScreenTime',
  'SecurityTest', 'SentimentAnalysis', 'ServiceOff', 'SettingsAdd', 'SettingsSecure', 'SettingsSync',
  'SharedDatabase', 'Sharepoint2013LogoInverse', 'ShowVisualFilter', 'Showers', 'SixPointStar', 'SkipBack10',
  'SkipForward30', 'Sleet', 'SortLinesAscending', 'Spelling', 'SquareShape', 'StorageAcount',
  'StreamDiscover', 'SwiftLogo', 'SwitchUser', 'TableBrandedColumn', 'TableBrandedRow', 'TableColumn',
  'TableFirstColumn', 'TableHeaderRow', 'TableLastColumn', 'TableTotalRow', 'TagGroup', 'TaskList',
  'TemporaryAccessPass', 'TestAdd', 'TestRemove', 'TextAlignBottom', 'TextAlignMiddle', 'TextAlignTop',
  'TextDocumentEdit', 'TextDocumentSettings', 'TextParagraphOption', 'TextRecognition', 'TextRotate270Degrees', 'TextRotate90Degrees',
  'TextRotateHorizontal', 'TextRotation', 'Total', 'TwelvePointStar', 'TwitterLogo', 'URLBlock',
  'UpdateRestore', 'Vaccination', 'Variable3', 'VideoOff2', 'ViewInAR', 'WebAppBuilderFragmentLock',
  'WebAppBuilderFragmentTest', 'WebAppBuilderModuleLock', 'WebAppBuilderModuleTest', 'WebEnvironment', 'XamarinLogo', 'XboxController',
  'XboxLogo', 'XboxOneConsole', 'iOSAppStoreLogo',
]);
