/**
 * genAppCss.mjs — bake the app stylesheet into `src/appCss.gen.ts` so the
 * panel can inject it into its shadow root.
 *
 * It lives apart from build.mjs because `src/panel.ts` imports the generated
 * module and the file is gitignored: the ROOT `npm test` needs it long before
 * anything in `spfx/panel` is built (root package.json's `pretest` runs this).
 * Node's `fs` only, no dependencies, and every path is resolved from this
 * file's own location, so it works from any working directory.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { cssForShadow } from './shadowCss.mjs';

const STYLE = new URL('../../../src/style.css', import.meta.url);
const ICONS = new URL('../../../src/chromeIcons.css', import.meta.url);
const OUT = new URL('../src/appCss.gen.ts', import.meta.url);

/** Write src/appCss.gen.ts from the parent repo's stylesheets. */
export async function genAppCss() {
  const css = cssForShadow((await readFile(STYLE, 'utf8')) + '\n' + (await readFile(ICONS, 'utf8')));
  await writeFile(OUT,
    '// GENERATED by tools/genAppCss.mjs — do not edit, do not commit.\nexport const APP_CSS = '
    + JSON.stringify(css) + ';\n');
  return OUT;
}

// `node spfx/panel/tools/genAppCss.mjs` (the root pretest) runs it directly;
// build.mjs imports and calls it instead.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await genAppCss();
