// Bundles the Format panel from the PARENT repo's src/ into one ESM file the
// SPFx webpack build consumes as a plain dependency (spike answer 2, variant
// A). Step 1 bakes the app stylesheet in as a string so the panel can inject
// it into its shadow root. Rebuilt by the SPFx project's prebuild/prestart.
import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { cssForShadow } from './tools/shadowCss.mjs';

const css = cssForShadow(
  (await readFile('../../src/style.css', 'utf8')) + '\n' + (await readFile('../../src/chromeIcons.css', 'utf8')),
);
await writeFile('src/appCss.gen.ts',
  '// GENERATED by build.mjs — do not edit, do not commit.\nexport const APP_CSS = ' + JSON.stringify(css) + ';\n');

await mkdir('dist', { recursive: true });
await build({
  entryPoints: ['src/panel.ts'],
  outfile: 'dist/panel.js',
  bundle: true,
  format: 'esm',
  target: 'es2022',
  sourcemap: true,
  legalComments: 'none',
  define: {
    __APP_VERSION__: JSON.stringify(process.env.npm_package_version ?? '0.0.0'),
    __BUILD_REV__: '"spfx"', __BUILD_DATE__: '""', __REPO_URL__: '""', __LAST_PR__: '""',
  },
});
console.log('formatfx-panel → dist/panel.js');
